[package]
name = "AptosERC20"
version = "0.0.1"
authors = ["example"]

[addresses]
addr = "0x35196d99ae6fed94c5133eb2bed70c87600f9b39e6e5912c2b0231c5fbf4d318"


[dependencies]
AptosFramework = { local = "../aptos-core/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "../aptos-core/aptos-move/framework/aptos-stdlib" }