[package]
name = "AptosERC20"
version = "0.0.1"
authors = ["example"]

[addresses]
token = "0x0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
